const KEY='referto-pallanuoto-v12';
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,7);
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const empty=()=>({settings:{teamName:'C.S. Plebiscito Padova',teamLogo:'',primary:'#1d9bf0'},seasons:[{id:'season-default',name:'2026/2027'}],currentSeasonId:'season-default',opponent:{name:'Avversaria',logo:''},home:true,match:{seasonId:'season-default',date:new Date().toISOString().slice(0,10),time:'',competitionType:'',competition:'',encounter:'',facility:'',venue:'',delegate:'',ref1:'',ref2:''},athletes:[],selected:[],events:[],timeouts:[null,null],saved:[]});
let state=load(); let currentAthlete=null,currentEvent=null,currentKind='shot',shotOutcome='Goal',situation='even',sanction='ET',assistType='goal',exclusionSide='against';
function load(){try{const raw=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('referto-pallanuoto-pwa-v11')||'null');if(!raw)return empty();const b=empty();const s={...b,...raw,settings:{...b.settings,...(raw.settings||{})},opponent:{...b.opponent,...(raw.opponent||{})},match:{...b.match,...(raw.match||{})}};s.seasons=Array.isArray(raw.seasons)&&raw.seasons.length?raw.seasons.map(x=>({id:x.id||uid(),name:String(x.name||'Stagione')})):[...b.seasons];s.currentSeasonId=raw.currentSeasonId&&s.seasons.some(x=>x.id===raw.currentSeasonId)?raw.currentSeasonId:s.seasons[0].id;s.athletes=Array.isArray(raw.athletes)?raw.athletes:[];s.saved=Array.isArray(raw.saved)?raw.saved:[];s.saved.forEach(x=>{if(!x.seasonId)x.seasonId=s.currentSeasonId;if(x.snapshot&&!x.snapshot.seasonId)x.snapshot.seasonId=x.seasonId});s.match.seasonId=s.match.seasonId&&s.seasons.some(x=>x.id===s.match.seasonId)?s.match.seasonId:s.currentSeasonId;s.selected=Array.isArray(raw.selected)?raw.selected.slice(0,15):[];s.events=Array.isArray(raw.events)?raw.events:((raw.match&&raw.match.events)||[]);s.timeouts=Array.isArray(raw.timeouts)?[raw.timeouts[0]||null,raw.timeouts[1]||null]:[null,null];s.athletes.forEach((a,i)=>{a.id=a.id||uid();a.name=a.name||`Atleta ${i+1}`;a.cap=String(a.cap||i+1);a.role=a.role||'';a.archived=!!a.archived});return s}catch{return empty()}}
function updateSaveStatus(){const el=document.getElementById('saveStatus');if(el){el.textContent='Auto-salvato';el.classList.add('saved');clearTimeout(window.__saveStatusTimer);window.__saveStatusTimer=setTimeout(()=>el.classList.remove('saved'),1200)}}
function save(){state._autoSavedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(state));updateSaveStatus();}
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function isRed(c){return String(c)==='1'||String(c)==='13'}
function capClass(a){if(!a)return 'cap-wp home'; if(isRed(a.cap))return 'cap-wp goalie'; return `cap-wp ${state.home?'home':'away'}`;}
function capHtml(a,extra=''){return `<span class="${capClass(a)} ${extra}"><i class="cap-ear left"></i><i class="cap-ear right"></i><span>${esc(a.cap)}</span></span>`}
function athlete(id){return state.athletes.find(a=>a.id===id)}
function selected(){return state.selected.map(athlete).filter(Boolean)}
function formatTime(v){let d=String(v??'').replace(/\D/g,'').slice(0,4);if(!d)return '';if(d.length<=2)return d.padStart(2,'0')+':00';return d.slice(0,-2).padStart(2,'0')+':'+d.slice(-2).padStart(2,'0')}
function bindTimeInput(el){el.addEventListener('input',()=>{let d=el.value.replace(/\D/g,'').slice(0,4);if(d.length>=3)el.value=d.slice(0,-2).padStart(2,'0')+':'+d.slice(-2);else el.value=d});el.addEventListener('blur',()=>{if(el.value)el.value=formatTime(el.value)})}
function ensureRoster(){if(state.athletes.length)return;for(let i=1;i<=15;i++)state.athletes.push({id:uid(),name:`Atleta ${i}`,cap:String(i),role:i===1?'Portiere':'',archived:false});state.selected=state.athletes.map(a=>a.id);save()}
function logo(img, fallback, src, text){if(src){$(img).src=src;$(img).classList.remove('hidden');$(fallback).classList.add('hidden')}else{$(img).classList.add('hidden');$(fallback).classList.remove('hidden');$(fallback).textContent=text}}
function currentSeason(){return (state.seasons||[]).find(x=>x.id===state.currentSeasonId)||(state.seasons||[])[0]||{id:'season-default',name:'Stagione'};}
function seasonName(id){return (state.seasons||[]).find(x=>x.id===id)?.name||currentSeason().name||'Stagione';}
function renderSeasonUI(){const sel=$('seasonSelect');if(sel){sel.innerHTML=(state.seasons||[]).map(x=>`<option value="${esc(x.id)}" ${x.id===state.currentSeasonId?'selected':''}>${esc(x.name)}</option>`).join('');}const lbl=$('currentSeasonLabel');if(lbl)lbl.textContent=currentSeason().name;const ss=$('settingsSeasonName');if(ss)ss.textContent=currentSeason().name;}
function saveSeasonChange(){save();renderArchive();renderSavedStats();}
function addSeason(){const name=prompt('Nome nuova stagione (es. 2027/2028):','2027/2028');if(!name?.trim())return;const id=uid();state.seasons.push({id,name:name.trim()});state.currentSeasonId=id;save();renderAll();toast('Nuova stagione creata');}
function renameSeason(){const cur=currentSeason();const name=prompt('Nuovo nome stagione:',cur.name);if(!name?.trim())return;cur.name=name.trim();save();renderAll();toast('Stagione rinominata');}
function deleteSeason(){const cur=currentSeason();if((state.seasons||[]).length<=1){toast('Deve rimanere almeno una stagione');return}const count=(state.saved||[]).filter(x=>x.seasonId===cur.id).length;if(count&& !confirm(`La stagione contiene ${count} partite salvate. Le partite verranno spostate nella stagione successiva. Continuare?`))return;const target=state.seasons.find(x=>x.id!==cur.id);(state.saved||[]).forEach(x=>{if(x.seasonId===cur.id){x.seasonId=target.id;if(x.snapshot)x.snapshot.seasonId=target.id}});state.seasons=state.seasons.filter(x=>x.id!==cur.id);state.currentSeasonId=target.id;save();renderAll();toast('Stagione eliminata');}
function renderHeader(){ renderSeasonUI(); $('appTitle').textContent='Referto Pallanuoto'; $('teamNameView').textContent=state.settings.teamName; $('opponentNameView').textContent=state.opponent.name||'Avversaria'; $('homeAwayText').textContent=state.home?'Siamo CASA':'Siamo FUORI CASA'; $('scoreTeamLabel').textContent=state.home?'CASA':'OSPITI'; $('scoreOppLabel').textContent=state.home?'OSPITI':'CASA'; logo('teamLogo','teamLogoFallback',state.settings.teamLogo,(state.settings.teamName||'WP').slice(0,2).toUpperCase());logo('opponentLogo','opponentLogoFallback',state.opponent.logo,(state.opponent.name||'AV').slice(0,2).toUpperCase());$('convCount').textContent=`${state.selected.length}/15`;const m=state.match;$('matchMetaView').textContent=[m.date&&new Date(m.date+'T00:00:00').toLocaleDateString('it-IT'),m.time,m.competitionType,m.competition,m.facility||m.venue,state.home?'':'FUORI CASA'].filter(Boolean).join(' · ')||'Anagrafica non compilata';}
function isGoalEvent(e){return e.kind==='shot'&&(e.outcome==='Goal'||e.outcome==='Goal subito')}
function calc(){const ev=state.events;const own=ev.filter(e=>isGoalEvent(e)&&e.team==='own').length;const against=ev.filter(e=>isGoalEvent(e)&&e.team==='against').length;return {own,against}}
function periodData(){const rows=[];for(let p=1;p<=4;p++){const gf=state.events.filter(e=>Number(e.period)===p&&isGoalEvent(e)&&e.team==='own').length;const ga=state.events.filter(e=>Number(e.period)===p&&isGoalEvent(e)&&e.team==='against').length;rows.push({p,gf,ga})}return rows}
function renderScore(){const c=calc();$('homeScore').textContent=state.home?c.own:c.against;$('awayScore').textContent=state.home?c.against:c.own;$('scoreView').textContent=`${state.home?c.own:c.against} — ${state.home?c.against:c.own}`;$('periodBadge').textContent=`${currentPeriod}° TEMPO`;const pd=periodData();$('periods').innerHTML=pd.map(x=>{const own=state.home?x.gf:x.ga,opp=state.home?x.ga:x.gf;return `<div class="period-card ${x.p===currentPeriod?'active':''}"><span>${x.p}°</span><strong>${own} : ${opp}</strong><small>parziale</small></div>`}).join('')}
let currentPeriod=1;
function registerGoalAgainst(goalieId){const a=athlete(goalieId);if(!a)return;state.events.push({id:uid(),athleteId:a.id,kind:'shot',period:currentPeriod,time:'00:00',note:'',team:'against',outcome:'Goal subito',situation:'even',sanction:null,exclusionSide:null,assistType:null,counter:false});save();renderAll();toast(`Goal subito dalla calotta ${a.cap}`)}
function exclusionMarks(a){const ex=state.events.filter(e=>e.athleteId===a.id&&e.kind==='exclusion'&&e.exclusionSide==='against');const hard=ex.some(e=>e.sanction==='EDCS'||e.sanction==='EDSS');const n=hard?3:Math.min(ex.length,3);if(n===0)return '';const marks=n===1?'<i class="ex-mark yellow1">1</i>':n===2?'<i class="ex-mark yellow1">1</i><i class="ex-mark yellow2">2</i>':'<i class="ex-mark yellow1">1</i><i class="ex-mark yellow2">2</i><i class="ex-mark red3">3</i>';return `<span class="ex-marks" title="Espulsioni prese contro: ${hard?'espulsione definitiva · 3/3':n+'/3'}">${marks}</span>`}
function renderPlayers(){const list=selected();$('players').innerHTML=list.length?list.map(a=>{const mine=state.events.filter(e=>e.athleteId===a.id);const goals=mine.filter(e=>isGoalEvent(e)&&e.team==='own').length;const ex=mine.filter(e=>e.kind==='exclusion'&&e.exclusionSide==='against').length;const hard=mine.some(e=>e.kind==='exclusion'&&e.exclusionSide==='against'&&(e.sanction==='EDCS'||e.sanction==='EDSS'));const goalie=a.role==='Portiere'||isRed(a.cap);return `<button class="player ${(ex>=3||hard)?'player-ex-danger':''}" data-player="${a.id}">${capHtml(a,goalie?'goalie-cap':'')}<span class="player-copy"><strong>${esc(a.name)}</strong><small>${esc(a.role||'Atleta')} · ${goals} goal</small></span>${exclusionMarks(a)}<span class="chev">›</span></button>`}).join(''):'<div class="empty">Nessuna convocata. Apri Convocate.</div>';document.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>openEvent(b.dataset.player))}
function renderTimeouts(){ $('timeoutGrid').innerHTML=[0,1].map(i=>{const t=state.timeouts[i];return `<div class="timeout-card ${t?'used':''}"><div><span class="label">TIME-OUT ${i+1}</span><strong>${t?`Usato · ${esc(t.period)} · ${esc(t.time)}`:'Non usato'}</strong></div><div class="timeout-actions"><button class="small-btn" data-timeout="${i}">${t?'Modifica':'Registra'}</button>${t?`<button class="icon-btn mini" data-timeout-clear="${i}">×</button>`:''}</div></div>`}).join('');document.querySelectorAll('[data-timeout]').forEach(b=>b.onclick=()=>editTimeout(Number(b.dataset.timeout)));document.querySelectorAll('[data-timeout-clear]').forEach(b=>b.onclick=()=>{state.timeouts[Number(b.dataset.timeoutClear)]=null;save();renderTimeouts()})}
function editTimeout(i){const old=state.timeouts[i]||{};const p=prompt('Tempo (1, 2, 3 o 4)',old.period||String(currentPeriod));if(!p)return;const t=prompt('Minuto MM:SS',old.time||'');if(t===null)return;state.timeouts[i]={period:p,time:formatTime(t)};save();renderTimeouts();toast(`Time-out ${i+1} salvato`)}
function eventLabel(e){const a=athlete(e.athleteId);let x=e.kind==='exclusion'?`${e.exclusionSide==='against'?'ESPULSIONE CONTRO':'ESPULSIONE A FAVORE'} · ${sanctionName(e.sanction)}`:e.kind==='assist'?assistName(e.assistType):e.outcome+(e.situation?` · ${sitName(e.situation)}`:'');return `${a?.name||'Atleta'} · ${x}`}
function assistName(v){return ({goal:'Assist goal',wrong:'Assist sbagliato',exclusion:'Assist per espulsione',penalty:'Assist per rigore'})[v]||'Assist'}
function sitName(s){return s==='even'?'Uomini pari':s==='power'?'Superiorità':'Contropiede'}function sanctionName(s){return ({ET:'E.T.',TR:'T.R.',EDCS:'E.D. C.S.',EDSS:'E.D. S.S.'})[s]||s}
function renderEvents(){const ev=[...state.events].reverse();$('eventCount').textContent=ev.length;$('eventLog').innerHTML=ev.length?ev.map(e=>`<div class="event-row"><div><span class="event-period">${e.period}° · ${esc(e.time||'--:--')}</span><strong>${esc(eventLabel(e))}</strong><small>${e.team==='against'?'Goal subito':' '}${e.note?` · ${esc(e.note)}`:''}</small></div><button class="edit-event" data-edit-event="${e.id}">✎</button></div>`).join(''):'<div class="empty">Nessun evento registrato.</div>';document.querySelectorAll('[data-edit-event]').forEach(b=>b.onclick=()=>openEvent(null,b.dataset.editEvent))}
function openEvent(id,eventId=null){currentEvent=eventId?state.events.find(e=>e.id===eventId):null;currentAthlete=id||currentEvent?.athleteId;const a=athlete(currentAthlete);if(!a)return;$('eventCap').className=capClass(a)+' event-dialog-cap';$('eventCap').innerHTML=`<i class="cap-ear left"></i><i class="cap-ear right"></i><span>${esc(a.cap)}</span>`;$('eventAthlete').textContent=a.name;$('eventRole').textContent=a.role||'Atleta';$('eventRole').dataset.role=a.role||'';currentKind=currentEvent?.kind||'shot';shotOutcome=currentEvent?.outcome||((a.role==='Portiere')?'Parata':'Goal');situation=currentEvent?.situation||'even';sanction=currentEvent?.sanction||'ET';assistType=currentEvent?.assistType||'goal';exclusionSide=currentEvent?.exclusionSide||'against';$('eventPeriod').value=currentEvent?.period||currentPeriod;$('eventTime').value=currentEvent?.time||'';$('eventNote').value=currentEvent?.note||'';renderEventPanel();$('deleteEvent').style.display=currentEvent?'inline-flex':'none';$('eventDialog').showModal()}
function renderEventPanel(){document.querySelectorAll('[data-kind]').forEach(b=>b.classList.toggle('selected',b.dataset.kind===currentKind));$('shotPanel').classList.toggle('hidden',currentKind!=='shot');$('exclusionPanel').classList.toggle('hidden',currentKind!=='exclusion');$('assistPanel').classList.toggle('hidden',currentKind!=='assist');const goalie=$('eventRole').dataset.role==='Portiere';$('shotChoices').innerHTML=goalie?'<button data-shot="Goal">GOAL A FAVORE</button><button data-shot="Goal subito">GOAL SUBITO</button><button data-shot="Parata">PARATA</button>':'<button data-shot="Goal">GOAL</button><button data-shot="Parato">PARATO</button><button data-shot="Fuori">FUORI</button>';document.querySelectorAll('[data-shot]').forEach(b=>{b.classList.toggle('selected',b.dataset.shot===shotOutcome);b.onclick=()=>{shotOutcome=b.dataset.shot;document.querySelectorAll('[data-shot]').forEach(x=>x.classList.toggle('selected',x.dataset.shot===shotOutcome))}});document.querySelectorAll('[data-situation]').forEach(b=>{b.classList.toggle('selected',b.dataset.situation===situation);b.onclick=()=>{situation=b.dataset.situation;document.querySelectorAll('[data-situation]').forEach(x=>x.classList.toggle('selected',x.dataset.situation===situation))}});document.querySelectorAll('[data-sanction]').forEach(b=>{b.classList.toggle('selected',b.dataset.sanction===sanction);b.onclick=()=>{sanction=b.dataset.sanction;document.querySelectorAll('[data-sanction]').forEach(x=>x.classList.toggle('selected',x.dataset.sanction===sanction))}});document.querySelectorAll('[data-assist]').forEach(b=>{b.classList.toggle('selected',b.dataset.assist===assistType);b.onclick=()=>{assistType=b.dataset.assist;document.querySelectorAll('[data-assist]').forEach(x=>x.classList.toggle('selected',x.dataset.assist===assistType))}});document.querySelectorAll('[data-exclusion-side]').forEach(b=>{b.classList.toggle('selected',b.dataset.exclusionSide===exclusionSide);b.onclick=()=>{exclusionSide=b.dataset.exclusionSide;document.querySelectorAll('[data-exclusion-side]').forEach(x=>x.classList.toggle('selected',x.dataset.exclusionSide===exclusionSide))}})}
function saveEvent(){const a=athlete(currentAthlete);if(!a)return;const obj={id:currentEvent?.id||uid(),athleteId:a.id,kind:currentKind,period:Number($('eventPeriod').value),time:formatTime($('eventTime').value)||'00:00',note:$('eventNote').value.trim(),team:currentKind==='shot'?(shotOutcome==='Goal'?'own':shotOutcome==='Goal subito'?'against':(a.role==='Portiere'?'against':'own')):(a.role==='Portiere'?'against':'own'),outcome:currentKind==='shot'?shotOutcome:currentKind==='assist'?'Assist goal':'Exclusion',situation:currentKind==='shot'?situation:null,sanction:currentKind==='exclusion'?sanction:null,exclusionSide:currentKind==='exclusion'?exclusionSide:null,assistType:currentKind==='assist'?assistType:null};if(currentEvent){const i=state.events.findIndex(e=>e.id===currentEvent.id);state.events[i]=obj}else state.events.push(obj);save();closeDialog('eventDialog');renderAll();toast('Evento salvato')}
function deleteEvent(){if(!currentEvent)return;state.events=state.events.filter(e=>e.id!==currentEvent.id);save();closeDialog('eventDialog');renderAll();toast('Evento eliminato')}
function renderStats(){const own=state.events.filter(e=>e.kind==='shot'&&e.outcome==='Goal'&&e.team==='own');const against=state.events.filter(e=>e.kind==='shot'&&e.outcome==='Goal'&&e.team==='against');const shots=state.events.filter(e=>e.kind==='shot'&&e.team==='own');const eff=shots.length?Math.round(own.length/shots.length*100):0;const assist=state.events.filter(e=>e.kind==='assist'&&e.outcome==='Assist goal').length;$('statsSummary').innerHTML=`<div class="stat-big"><span>FATTI</span><strong>${own.length}</strong></div><div class="stat-big"><span>SUBITI</span><strong>${against.length}</strong></div><div class="stat-big"><span>TIRI</span><strong>${shots.length}</strong></div><div class="stat-big"><span>EFFICACIA</span><strong>${eff}%</strong></div><div class="stat-big"><span>ASSIST</span><strong>${assist}</strong></div>`;const pd=periodData();$('statsPeriods').innerHTML=pd.map(x=>`<div class="period-stat"><span>${x.p}° tempo</span><strong>${x.gf} : ${x.ga}</strong></div>`).join('');const situations=[['even','Uomini pari'],['power','Superiorità'],['counter','Contropiede']];$('situationStats').innerHTML=situations.map(([s,n])=>{const made=own.filter(e=>e.situation===s).length;const missed=state.events.filter(e=>e.kind==='shot'&&e.team==='own'&&e.situation===s&&e.outcome!=='Goal').length;const con=against.filter(e=>e.situation===s).length;return `<div class="situation-card"><strong>${n}</strong><span>Goal fatti <b>${made}</b></span><span>Sbagliati <b>${missed}</b></span><span>Goal subiti <b>${con}</b></span></div>`}).join('');const ex=state.events.filter(e=>e.kind==='exclusion');$('exclusionStats').innerHTML=selected().map(a=>{const n=ex.filter(e=>e.athleteId===a.id&&e.exclusionSide==='against').length;const fav=ex.filter(e=>e.athleteId===a.id&&e.exclusionSide==='for').length;return `<div class="ex-row ${n>=3?'ex-danger':''}">${capHtml(a,'mini')}<strong>${esc(a.name)}</strong><span class="ex-count">${n}/3</span><small>favore ${fav}</small></div>`}).join('')||'<div class="empty">Nessuna espulsione.</div>';$('statsTable').innerHTML=selected().map(a=>{const es=state.events.filter(e=>e.athleteId===a.id);const gs=es.filter(e=>e.kind==='shot'&&e.team==='own'&&e.outcome==='Goal').length;const ts=es.filter(e=>e.kind==='shot'&&e.team==='own').length;const sup=es.filter(e=>e.kind==='shot'&&e.situation==='power'&&e.outcome==='Goal').length;const pari=es.filter(e=>e.kind==='shot'&&e.situation==='even'&&e.outcome==='Goal').length;const cp=es.filter(e=>e.kind==='shot'&&e.situation==='counter'&&e.outcome==='Goal').length;const as=es.filter(e=>e.kind==='assist').length;const exn=es.filter(e=>e.kind==='exclusion'&&e.exclusionSide==='against').length;return `<tr><td>${esc(a.name)}</td><td>${gs}</td><td>${ts}</td><td>${ts?Math.round(gs/ts*100):0}%</td><td>${sup}</td><td>${pari}</td><td>${cp}</td><td>${as}</td><td>${exn}</td></tr>`}).join('')}
function getSavedStatsSnapshot(s){return s?.snapshot||s?.state||null}
function savedSummary(s){const snap=getSavedStatsSnapshot(s)||{};const ev=Array.isArray(snap.events)?snap.events:[];const own=ev.filter(e=>e.kind==='shot'&&e.outcome==='Goal'&&e.team==='own').length;const against=ev.filter(e=>e.kind==='shot'&&e.outcome==='Goal'&&e.team==='against').length;const shots=ev.filter(e=>e.kind==='shot'&&e.team==='own').length;const assists=ev.filter(e=>e.kind==='assist'&&e.assistType==='goal').length;const exAgainst=ev.filter(e=>e.kind==='exclusion'&&e.exclusionSide==='against').length;const exFor=ev.filter(e=>e.kind==='exclusion'&&e.exclusionSide==='for').length;return {own,against,shots,assists,exAgainst,exFor}}
function renderSavedStats(){const box=$('savedStatsMatches'),sum=$('savedStatsSummary'),tbl=$('savedStatsTable');if(!box||!sum||!tbl)return;const list=(state.saved||[]).filter(s=>s.seasonId===state.currentSeasonId);box.innerHTML=list.length?list.map((s,i)=>{const q=savedSummary(s);const m=s.match||{};const title=`${s.teamName||state.settings.teamName} ${s.home?'vs':'@'} ${s.opponent||'Avversaria'}`;return `<label class="saved-stat-row"><input type="checkbox" data-saved-stat="${esc(s.id)}"><span><strong>${esc(title)}</strong><small>${esc(fmtDate(m.date)||'')}${m.time?' · '+esc(m.time):''}${m.competitionType?' · '+esc(m.competitionType):''}</small></span><b>${q.own}-${q.against}</b></label>`}).join(''):'<div class="empty">Salva almeno una partita per confrontare le statistiche.</div>';const update=()=>{const ids=[...document.querySelectorAll('[data-saved-stat]:checked')].map(x=>x.dataset.savedStat);const chosen=list.filter(s=>ids.includes(s.id));const agg=chosen.reduce((a,s)=>{const q=savedSummary(s);Object.keys(q).forEach(k=>a[k]+=q[k]);a.matches++;return a},{matches:0,own:0,against:0,shots:0,assists:0,exAgainst:0,exFor:0});sum.innerHTML=`<div class="stat-big"><span>PARTITE</span><strong>${agg.matches}</strong></div><div class="stat-big"><span>GOAL FATTI</span><strong>${agg.own}</strong></div><div class="stat-big"><span>GOAL SUBITI</span><strong>${agg.against}</strong></div><div class="stat-big"><span>TIRI</span><strong>${agg.shots}</strong></div><div class="stat-big"><span>ASSIST GOAL</span><strong>${agg.assists}</strong></div><div class="stat-big"><span>ESP. CONTRO</span><strong>${agg.exAgainst}</strong></div><div class="stat-big"><span>ESP. A FAVORE</span><strong>${agg.exFor}</strong></div>`;tbl.innerHTML=chosen.length?chosen.map(s=>{const q=savedSummary(s),m=s.match||{};return `<tr><td>${esc(fmtDate(m.date)||'')}</td><td>${esc(s.opponent||'')}</td><td>${q.own}</td><td>${q.against}</td><td>${q.shots}</td><td>${q.assists}</td><td>${q.exAgainst}</td><td>${q.exFor}</td></tr>`}).join(''):'<tr><td colspan="8" class="empty-cell">Seleziona le partite da analizzare</td></tr>'};document.querySelectorAll('[data-saved-stat]').forEach(x=>x.onchange=update);update()}
function renderArchive(){const rows=state.saved.filter(s=>s.seasonId===state.currentSeasonId).map(s=>`<div class="archive-row"><div><strong>${esc(s.teamName)} ${s.home?'vs':'@'} ${esc(s.opponent)}</strong><small>${esc(s.match.date||'')}${s.match.time?` · ${esc(s.match.time)}`:''} · ${esc(s.match.competitionType||'')}${s.match.competition?` · ${esc(s.match.competition)}`:''}</small></div><button class="small-btn" data-open-save="${s.id}">Apri</button><button class="danger-btn archive-delete" data-del-save="${s.id}" title="Elimina partita">🗑 Elimina</button></div>`).join('');$('archiveList').innerHTML=rows||'<div class="empty">Nessuna partita salvata.</div>';$('archiveDialogList').innerHTML=rows||'<div class="empty">Nessuna partita salvata.</div>';bindArchiveButtons()}
function bindArchiveButtons(){document.querySelectorAll('[data-open-save]').forEach(b=>b.onclick=()=>{const s=state.saved.find(x=>x.id===b.dataset.openSave);if(!s)return;const archive=state.saved||[];const seasons=JSON.parse(JSON.stringify(state.seasons||[]));state=JSON.parse(JSON.stringify(s.snapshot));state.seasons=seasons;state.saved=archive;state.currentSeasonId=s.seasonId||state.currentSeasonId||seasons[0]?.id||'season-default';state.match.seasonId=state.currentSeasonId;save();renderAll();showPage('match');toast('Partita caricata')});document.querySelectorAll('[data-del-save]').forEach(b=>b.onclick=()=>{if(confirm('Eliminare definitivamente questa partita salvata? I dati della partita verranno rimossi dall’archivio di questa stagione.')){state.saved=state.saved.filter(x=>x.id!==b.dataset.delSave);save();renderArchive();renderSavedStats();toast('Partita eliminata dall’archivio')}})}
function saveMatch(){state.match.seasonId=state.currentSeasonId;const snap=JSON.parse(JSON.stringify({...state,saved:[]}));state.saved.unshift({id:uid(),seasonId:state.currentSeasonId,teamName:state.settings.teamName,opponent:state.opponent.name,home:state.home,match:JSON.parse(JSON.stringify(state.match)),snapshot:snap,savedAt:new Date().toISOString()});save();renderArchive();toast('Partita salvata')}
function openMatchData(){const m=state.match;$('mDate').value=m.date||'';$('mTime').value=m.time||'';$('mCompetitionType').value=m.competitionType||'';$('mCompetition').value=m.competition||'';$('mEncounter').value=m.encounter||'';$('mFacility').value=m.facility||m.venue||'';$('mDelegate').value=m.delegate||'';$('mRef1').value=m.ref1||'';$('mRef2').value=m.ref2||'';$('homeAwayCheck').checked=!state.home;$('homeBtn').classList.toggle('selected',state.home);$('awayBtn').classList.toggle('selected',!state.home);$('matchDialog').showModal()}
function saveMatchData(){state.home=!$('homeAwayCheck').checked;state.match={seasonId:state.currentSeasonId,date:$('mDate').value,time:$('mTime').value,competitionType:$('mCompetitionType').value.trim(),competition:$('mCompetition').value.trim(),encounter:$('mEncounter').value.trim(),facility:$('mFacility').value.trim(),venue:$('mFacility').value.trim(),delegate:$('mDelegate').value.trim(),ref1:$('mRef1').value.trim(),ref2:$('mRef2').value.trim()};save();closeDialog('matchDialog');renderAll();toast(state.home?'Incontro impostato CASA':'Incontro impostato FUORI CASA')}
function openConv(){const active=state.athletes.filter(a=>!a.archived);$('convList').innerHTML=`<div class="conv-toolbar"><strong>Seleziona le atlete</strong><span id="convLiveCount">${state.selected.length}/15</span></div>`+active.map(a=>`<label class="conv-card ${state.selected.includes(a.id)?'selected':''}"><input type="checkbox" data-conv="${a.id}" ${state.selected.includes(a.id)?'checked':''}><span class="conv-check">✓</span>${capHtml(a,'mini')}<span class="conv-copy"><b>${esc(a.name)}</b><small>${esc(a.role||'Atleta')}</small></span></label>`).join('');$('convDialog').showModal();document.querySelectorAll('[data-conv]').forEach(x=>x.onchange=()=>{if(document.querySelectorAll('[data-conv]:checked').length>15){x.checked=false;toast('Massimo 15 convocate')}x.closest('.conv-card').classList.toggle('selected',x.checked);const c=document.querySelectorAll('[data-conv]:checked').length;const el=$('convLiveCount');if(el)el.textContent=`${c}/15`})}
function saveConv(){state.selected=[...document.querySelectorAll('[data-conv]:checked')].map(x=>x.dataset.conv).slice(0,15);save();closeDialog('convDialog');renderAll();toast('Convocazione salvata')}
function openSettings(){ $('sTeam').value=state.settings.teamName;$('sOpp').value=state.opponent.name;$('sColor').value=state.settings.primary;$('teamLogoPreview').innerHTML=state.settings.teamLogo?`<img src="${state.settings.teamLogo}">`:'';$('oppLogoPreview').innerHTML=state.opponent.logo?`<img src="${state.opponent.logo}">`:'';renderManager();$('settingsDialog').showModal()}
function readImage(input,cb){const f=input.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
function renderManager(){$('rosterManager').innerHTML=state.athletes.map(a=>`<div class="manager-row ${a.archived?'muted':''}">${capHtml(a,'mini')}<input data-name="${a.id}" value="${esc(a.name)}"><input data-cap="${a.id}" value="${esc(a.cap)}"><select data-role="${a.id}"><option value="" ${!a.role?'selected':''}>Atleta</option><option value="Portiere" ${a.role==='Portiere'?'selected':''}>Portiere</option></select><button class="icon-btn mini" data-archive="${a.id}">${a.archived?'↩':'⌁'}</button></div>`).join('')||'<div class="empty">Nessuna atleta.</div>';document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{const a=athlete(b.dataset.archive);a.archived=!a.archived;if(a.archived)state.selected=state.selected.filter(id=>id!==a.id);save();renderManager();renderPlayers();})}
function saveSettings(){state.settings.teamName=$('sTeam').value.trim()||'Squadra';state.opponent.name=$('sOpp').value.trim()||'Avversaria';state.settings.primary=$('sColor').value;document.querySelectorAll('[data-name]').forEach(i=>{const a=athlete(i.dataset.name);if(a)a.name=i.value.trim()||a.name});document.querySelectorAll('[data-cap]').forEach(i=>{const a=athlete(i.dataset.cap);if(a)a.cap=i.value.trim()||a.cap});document.querySelectorAll('[data-role]').forEach(i=>{const a=athlete(i.dataset.role);if(a)a.role=i.value});save();closeDialog('settingsDialog');renderAll();toast('Dati salvati')}
function addAthlete(){let n=state.athletes.length+1;state.athletes.push({id:uid(),name:`Atleta ${n}`,cap:String(n),role:'',archived:false});save();renderManager();}
function showPage(p){['match','stats','archive'].forEach(x=>{$(`${x}Page`).classList.toggle('hidden',x!==p)});document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));$(`tab${p[0].toUpperCase()+p.slice(1)}`).classList.add('active');if(p==='stats'){renderStats();renderSavedStats()}if(p==='archive')renderArchive()}
function closeDialog(id){$(id).close?.();$(id).removeAttribute('open')}
function renderAll(){renderHeader();renderScore();renderTimeouts();renderPlayers();renderEvents();renderStats();renderArchive();renderSavedStats()}
// EXPORT PDF / EXCEL
function reportTitle(){
  const m=state.match||{};
  return `${state.settings.teamName||'Squadra'} ${state.home?'vs':'@'} ${state.opponent.name||'Avversaria'}`;
}
function fmtDate(v){if(!v)return '';try{return new Date(v+'T00:00:00').toLocaleDateString('it-IT')}catch{return v}}
function reportMeta(){
  const m=state.match||{};
  return [
    ['Data',fmtDate(m.date)],['Ora partita',m.time||''],['Tipo campionato',m.competitionType||''],
    ['Campionato / Girone',m.competition||''],['Incontro',m.encounter||`${state.home?state.settings.teamName:state.opponent.name} vs ${state.home?state.opponent.name:state.settings.teamName}`],
    ['Impianto / Piscina',m.facility||m.venue||''],['Delegato',m.delegate||''],['Arbitro 1',m.ref1||''],['Arbitro 2',m.ref2||''],['Sede',state.home?'CASA':'FUORI CASA']
  ];
}
function reportLogo(src,alt){return src?`<img class="report-logo" src="${src}" alt="${esc(alt)}">`:''}
function reportRowsEvents(){
  const ev=[...state.events].sort((a,b)=>Number(a.period)-Number(b.period)||String(a.time||'').localeCompare(String(b.time||'')));
  return ev.map(e=>{const a=athlete(e.athleteId);return `<tr><td>${esc(e.period||'')}</td><td>${esc(e.time||'')}</td><td>${esc(a?.cap||'')}</td><td>${esc(a?.name||'Atleta')}</td><td>${esc(eventLabel(e))}</td><td>${esc(e.team==='against'?'Subito':'Fatto')}</td><td>${esc(e.note||'')}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty-cell">Nessun evento registrato</td></tr>';
}
function reportRowsAthletes(){
  return selected().map(a=>{const es=state.events.filter(e=>e.athleteId===a.id);const gs=es.filter(e=>e.kind==='shot'&&e.team==='own'&&e.outcome==='Goal').length;const ts=es.filter(e=>e.kind==='shot'&&e.team==='own').length;const sup=es.filter(e=>e.kind==='shot'&&e.situation==='power'&&e.outcome==='Goal').length;const pari=es.filter(e=>e.kind==='shot'&&e.situation==='even'&&e.outcome==='Goal').length;const cp=es.filter(e=>e.kind==='shot'&&e.situation==='counter'&&e.outcome==='Goal').length;const assists=es.filter(e=>e.kind==='assist').length;const ex=es.filter(e=>e.kind==='exclusion').length;const conceded=es.filter(e=>e.kind==='shot'&&e.team==='against'&&e.outcome==='Goal').length;return `<tr><td>${esc(a.cap)}</td><td>${esc(a.name)}</td><td>${esc(a.role||'Atleta')}</td><td>${gs}</td><td>${conceded}</td><td>${ts}</td><td>${ts?Math.round(gs/ts*100):0}%</td><td>${sup}</td><td>${pari}</td><td>${cp}</td><td>${assists}</td><td>${ex}</td></tr>`}).join('')||'<tr><td colspan="12" class="empty-cell">Nessuna convocata</td></tr>';
}
function reportRowsTimeouts(){
  return state.timeouts.map((t,i)=>`<tr><td>Time-out ${i+1}</td><td>${esc(t?.period?`${t.period}° tempo`:'—')}</td><td>${esc(t?.time||'—')}</td></tr>`).join('');
}
function buildPrintReport(){
  const c=calc(), pd=periodData(), m=state.match||{};
  const situations=[['even','Uomini pari'],['power','Superiorità'],['counter','Contropiede']];
  const logoLeft=state.home?state.settings.teamLogo:state.opponent.logo, logoRight=state.home?state.opponent.logo:state.settings.teamLogo;
  const teamLeft=state.home?state.settings.teamName:state.opponent.name, teamRight=state.home?state.opponent.name:state.settings.teamName;
  const situationRows=situations.map(([s,n])=>{const made=state.events.filter(e=>e.kind==='shot'&&e.team==='own'&&e.situation===s&&e.outcome==='Goal').length;const missed=state.events.filter(e=>e.kind==='shot'&&e.team==='own'&&e.situation===s&&e.outcome!=='Goal').length;const con=state.events.filter(e=>e.kind==='shot'&&e.team==='against'&&e.situation===s&&e.outcome==='Goal').length;return `<tr><td>${n}</td><td>${made}</td><td>${missed}</td><td>${con}</td></tr>`}).join('');
  return `<!doctype html><html lang="it"><head><meta charset="utf-8"><title>Referto - ${esc(reportTitle())}</title><style>
  @page{size:A4 portrait;margin:12mm 12mm 14mm}*{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#172335;margin:0;background:#fff;font-size:9.5pt;line-height:1.35}.page{page-break-after:always}.page:last-child{page-break-after:auto}.header{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #173b5d;padding-bottom:8px;margin-bottom:12px}.brand{display:flex;align-items:center;gap:10px}.report-logo{width:48px;height:48px;object-fit:contain}.brand h1{font-size:18pt;margin:0}.brand small{color:#60748c}.score{display:flex;align-items:center;justify-content:center;gap:24px;margin:14px 0 18px}.team{width:35%;text-align:center;font-weight:800;font-size:12pt}.scorebox{font-size:24pt;font-weight:900;white-space:nowrap}.sub{color:#60748c;font-size:8pt;margin-top:2px}.section{margin:0 0 14px}.section h2{font-size:11pt;margin:0 0 6px;border-bottom:1px solid #b9c6d3;padding-bottom:4px;color:#173b5d}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px 20px}.meta{border:1px solid #d5dde5;border-radius:5px;padding:8px}.meta-row{display:flex;gap:7px;padding:2px 0}.meta-row b{min-width:120px;color:#4b6178}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.card{border:1px solid #d5dde5;padding:7px;text-align:center;border-radius:4px}.card b{display:block;font-size:14pt}.card span{font-size:7.5pt;color:#60748c}table{width:100%;border-collapse:collapse;margin-top:5px}th{background:#173b5d;color:#fff;text-align:left;font-size:7.5pt;padding:5px}td{border:1px solid #d7dee6;padding:4px;font-size:8pt;vertical-align:top}tr{page-break-inside:avoid}.empty-cell{text-align:center;color:#77899b;padding:10px}.footer{margin-top:12px;border-top:1px solid #d7dee6;padding-top:5px;font-size:7pt;color:#718197;display:flex;justify-content:space-between}.small-note{font-size:7.5pt;color:#60748c}.nowrap{white-space:nowrap}.print-only-title{font-size:8pt;color:#60748c;margin-bottom:3px}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
  </style></head><body>
  <div class="page"><div class="header"><div class="brand">${reportLogo(state.settings.teamLogo,state.settings.teamName)}<div><h1>REFerto PALLANUOTO</h1><small>Referto digitale · report partita</small></div></div><div class="sub">${esc(fmtDate(m.date))}${m.time?' · '+esc(m.time):''}</div></div>
    <div class="score"><div class="team">${reportLogo(logoLeft,teamLeft)}<div>${esc(teamLeft)}</div><div class="sub">${state.home?'CASA':'OSPITI'}</div></div><div class="scorebox">${c.own} — ${c.against}</div><div class="team">${reportLogo(logoRight,teamRight)}<div>${esc(teamRight)}</div><div class="sub">${state.home?'OSPITI':'CASA'}</div></div></div>
    <div class="section"><h2>ANAGRAFICA INCONTRO</h2><div class="grid2">${reportMeta().map(x=>`<div class="meta-row"><b>${esc(x[0])}</b><span>${esc(x[1]||'—')}</span></div>`).join('')}</div></div>
    <div class="section"><h2>PARZIALI</h2><div class="cards">${pd.map(x=>`<div class="card"><span>${x.p}° TEMPO</span><b>${x.gf} : ${x.ga}</b></div>`).join('')}</div></div>
    <div class="section"><h2>TIME-OUT</h2><table><thead><tr><th>Time-out</th><th>Tempo</th><th>Minuto</th></tr></thead><tbody>${reportRowsTimeouts()}</tbody></table></div>
    <div class="section"><h2>RIEPILOGO STATISTICO</h2><div class="cards"><div class="card"><span>GOAL FATTI</span><b>${c.own}</b></div><div class="card"><span>GOAL SUBITI</span><b>${c.against}</b></div><div class="card"><span>TIRI</span><b>${state.events.filter(e=>e.kind==='shot'&&e.team==='own').length}</b></div><div class="card"><span>ASSIST</span><b>${state.events.filter(e=>e.kind==='assist').length}</b></div></div></div>
    <div class="footer"><span>${esc(state.settings.teamName)}</span><span>Pagina 1</span></div>
  </div>
  <div class="page"><div class="header"><div class="brand"><div><h1>STATISTICHE E SITUAZIONI</h1><small>${esc(reportTitle())}</small></div></div></div>
    <div class="section"><h2>GOAL FATTI / SBAGLIATI / SUBITI</h2><table><thead><tr><th>Situazione</th><th>Goal fatti</th><th>Sbagliati</th><th>Goal subiti</th></tr></thead><tbody>${situationRows}</tbody></table></div>
    <div class="section"><h2>STATISTICHE INDIVIDUALI</h2><table><thead><tr><th>N°</th><th>Atleta</th><th>Ruolo</th><th>Goal</th><th>Subiti</th><th>Tiri</th><th>%</th><th>Sup.</th><th>Pari</th><th>Controp.</th><th>Assist</th><th>Esp.</th></tr></thead><tbody>${reportRowsAthletes()}</tbody></table></div>
    <div class="section"><h2>DISCIPLINA</h2><table><thead><tr><th>Tempo</th><th>Minuto</th><th>Atleta</th><th>Sanzione</th><th>Nota</th></tr></thead><tbody>${state.events.filter(e=>e.kind==='exclusion').sort((a,b)=>Number(a.period)-Number(b.period)).map(e=>{const a=athlete(e.athleteId);return `<tr><td>${esc(e.period+'°')}</td><td>${esc(e.time||'')}</td><td>${esc(a?.cap||'')} · ${esc(a?.name||'')}</td><td>${esc(sanctionName(e.sanction))}</td><td>${esc(e.note||'')}</td></tr>`}).join('')||'<tr><td colspan="5" class="empty-cell">Nessuna sanzione</td></tr>'}</tbody></table></div>
    <div class="footer"><span>${esc(state.settings.teamName)}</span><span>Statistiche</span></div>
  </div>
  <div class="page"><div class="header"><div class="brand"><div><h1>CRONOLOGIA EVENTI</h1><small>${esc(reportTitle())}</small></div></div></div>
    <table><thead><tr><th>Tempo</th><th>Minuto</th><th>N°</th><th>Atleta</th><th>Evento</th><th>Esito</th><th>Nota</th></tr></thead><tbody>${reportRowsEvents()}</tbody></table>
    <div class="footer"><span>Documento generato dal Referto Pallanuoto</span><span>Eventi: ${state.events.length}</span></div>
  </div>
  <script>window.onload=()=>setTimeout(()=>window.print(),350)<\/script></body></html>`;
}
function exportPDF(){
  const w=window.open('','_blank');
  if(!w){toast('Consenti i popup per esportare il PDF');return}
  w.document.open();w.document.write(buildPrintReport());w.document.close();
}
function xmlEsc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;')}
function xCell(v,style='sText',type='String'){return `<Cell ss:StyleID="${style}"><Data ss:Type="${type}">${xmlEsc(v)}</Data></Cell>`}
function xRow(cells){return `<Row>${cells.join('')}</Row>`}
function excelSheet(name,rows){
  const widths=rows[0]?.map(()=>80)||[];
  return `<Worksheet ss:Name="${xmlEsc(name)}"><Table>${rows.map(r=>xRow(r)).join('')}</Table><WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel"><PageSetup><Layout x:Orientation="Landscape"/><PageMargins x:Top="0.35" x:Bottom="0.35" x:Left="0.3" x:Right="0.3"/></PageSetup><FitToPage/><Print><ValidPrinterInfo/><PaperSizeIndex>9</PaperSizeIndex><HorizontalResolution>600</HorizontalResolution><VerticalResolution>600</VerticalResolution><FitWidth>1</FitWidth><FitHeight>0</FitHeight></Print><Selected/></WorksheetOptions></Worksheet>`;
}
function exportExcel(){
  const c=calc(),pd=periodData(),m=state.match||{};
  const rowsSummary=[
    [xCell('REFERTO PALLANUOTO','sTitle'),xCell(reportTitle(),'sTitle')],
    [xCell('ANAGRAFICA','sSection'),xCell('','sSection')],
    ...reportMeta().map(r=>[xCell(r[0],'sLabel'),xCell(r[1]||'','sText')]),
    [xCell('RISULTATO','sSection'),xCell(`${c.own} - ${c.against}`,'sBig')],
    [xCell('','sText')],
    [xCell('PARZIALI','sSection'),xCell('','sSection')],
    ...pd.map(x=>[xCell(`${x.p}° tempo`,'sLabel'),xCell(`${x.gf} - ${x.ga}`,'sText')]),
    [xCell('','sText')],
    [xCell('TIME-OUT','sSection'),xCell('Tempo','sHeader'),xCell('Minuto','sHeader')],
    ...state.timeouts.map((t,i)=>[xCell(`Time-out ${i+1}`),xCell(t?.period?`${t.period}° tempo`:'—'),xCell(t?.time||'—')])
  ];
  const rowsEvents=[[xCell('CRONOLOGIA EVENTI','sTitle')],[xCell('Tempo','sHeader'),xCell('Minuto','sHeader'),xCell('N°','sHeader'),xCell('Atleta','sHeader'),xCell('Evento','sHeader'),xCell('Esito','sHeader'),xCell('Situazione','sHeader'),xCell('Nota','sHeader')],...state.events.map(e=>{const a=athlete(e.athleteId);return [xCell(e.period+'°'),xCell(e.time||''),xCell(a?.cap||''),xCell(a?.name||''),xCell(eventLabel(e)),xCell(e.team==='against'?'Subito':'Fatto'),xCell(e.situation?sitName(e.situation):''),xCell(e.note||'')]})];
  const rowsAth=[[xCell('STATISTICHE INDIVIDUALI','sTitle')],[...['N°','Atleta','Ruolo','Goal','Subiti','Tiri','%','Superiorità','Pari','Contropiede','Assist','Espulsioni'].map(v=>xCell(v,'sHeader'))],...selected().map(a=>{const es=state.events.filter(e=>e.athleteId===a.id);const gs=es.filter(e=>e.kind==='shot'&&e.team==='own'&&e.outcome==='Goal').length;const con=es.filter(e=>e.kind==='shot'&&e.team==='against'&&e.outcome==='Goal').length;const ts=es.filter(e=>e.kind==='shot'&&e.team==='own').length;return [xCell(a.cap),xCell(a.name),xCell(a.role||'Atleta'),xCell(gs,'sNum','Number'),xCell(con,'sNum','Number'),xCell(ts,'sNum','Number'),xCell(ts?Math.round(gs/ts*100):0,'sNum','Number'),xCell(es.filter(e=>e.situation==='power'&&e.outcome==='Goal').length,'sNum','Number'),xCell(es.filter(e=>e.situation==='even'&&e.outcome==='Goal').length,'sNum','Number'),xCell(es.filter(e=>e.situation==='counter'&&e.outcome==='Goal').length,'sNum','Number'),xCell(es.filter(e=>e.kind==='assist').length,'sNum','Number'),xCell(es.filter(e=>e.kind==='exclusion').length,'sNum','Number')]})];
  const rowsSitu=[[xCell('SITUAZIONI','sTitle')],[xCell('Situazione','sHeader'),xCell('Goal fatti','sHeader'),xCell('Sbagliati','sHeader'),xCell('Goal subiti','sHeader')],...['even','power','counter'].map(s=>[xCell(sitName(s)),xCell(state.events.filter(e=>e.kind==='shot'&&e.team==='own'&&e.situation===s&&e.outcome==='Goal').length,'sNum','Number'),xCell(state.events.filter(e=>e.kind==='shot'&&e.team==='own'&&e.situation===s&&e.outcome!=='Goal').length,'sNum','Number'),xCell(state.events.filter(e=>e.kind==='shot'&&e.team==='against'&&e.situation===s&&e.outcome==='Goal').length,'sNum','Number')])];
  const xml=`<?xml version="1.0" encoding="UTF-8"?><?mso-application progid="Excel.Sheet"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Styles><Style ss:ID="Default" ss:Name="Normal"><Alignment ss:Vertical="Center"/><Font ss:FontName="Arial" ss:Size="10"/></Style><Style ss:ID="sTitle"><Font ss:Bold="1" ss:Size="16"/><Interior ss:Color="#173B5D" ss:Pattern="Solid"/><Font ss:Color="#FFFFFF" ss:Bold="1" ss:Size="16"/></Style><Style ss:ID="sSection"><Font ss:Bold="1" ss:Size="11" ss:Color="#173B5D"/></Style><Style ss:ID="sHeader"><Font ss:Bold="1" ss:Color="#FFFFFF"/><Interior ss:Color="#173B5D" ss:Pattern="Solid"/></Style><Style ss:ID="sLabel"><Font ss:Bold="1" ss:Color="#4B6178"/></Style><Style ss:ID="sBig"><Font ss:Bold="1" ss:Size="18"/></Style><Style ss:ID="sNum"><NumberFormat ss:Format="0"/></Style><Style ss:ID="sText"/></Styles>${excelSheet('Riepilogo',rowsSummary)}${excelSheet('Eventi',rowsEvents)}${excelSheet('Atlete',rowsAth)}${excelSheet('Situazioni',rowsSitu)}</Workbook>`;
  const blob=new Blob([xml],{type:'application/vnd.ms-excel'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`referto-${(state.settings.teamName||'squadra').replace(/[^a-z0-9àèéìòù_-]+/gi,'_')}-${m.date||new Date().toISOString().slice(0,10)}.xml`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Excel esportato');
}

$('saveMatchBtn').onclick=saveMatch;
// events UI
$('eventKinds').querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{currentKind=b.dataset.kind;renderEventPanel()});$('saveEvent').onclick=saveEvent;$('exportPdfBtn').onclick=exportPDF;$('exportExcelBtn').onclick=exportExcel;$('deleteEvent').onclick=deleteEvent;$('shareBtn').onclick=()=>{const text=`${state.settings.teamName} vs ${state.opponent.name}\n${calc().own}-${calc().against}`;navigator.share?navigator.share({title:'Referto',text}):navigator.clipboard?.writeText(text).then(()=>toast('Copiato'))};
// tabs
$('tabMatch').onclick=()=>showPage('match');$('tabStats').onclick=()=>showPage('stats');$('tabArchive').onclick=()=>showPage('archive');
$('matchDataBtn').onclick=openMatchData;$('saveMatchData').onclick=saveMatchData;$('convocationBtn').onclick=openConv;$('saveConv').onclick=saveConv;$('settingsBtn').onclick=openSettings;$('addAthlete').onclick=addAthlete;$('saveSettings').onclick=saveSettings;$('manageRosterBtn').onclick=openSettings;$('saveMatchData').onclick=saveMatchData;$('homeBtn').onclick=()=>{state.home=true;$('homeAwayCheck').checked=false;$('homeBtn').classList.add('selected');$('awayBtn').classList.remove('selected');save();renderHeader();renderPlayers()};$('awayBtn').onclick=()=>{state.home=false;$('homeAwayCheck').checked=true;$('awayBtn').classList.add('selected');$('homeBtn').classList.remove('selected');save();renderHeader();renderPlayers()};$('homeAwayCheck').onchange=()=>{state.home=!$('homeAwayCheck').checked;$('homeBtn').classList.toggle('selected',state.home);$('awayBtn').classList.toggle('selected',!state.home);save();renderHeader();renderPlayers();renderScore()};$('newMatchBtn').onclick=()=>{if(confirm('Creare una nuova partita?')){const t=state.settings.teamName;state.match={seasonId:state.currentSeasonId,date:new Date().toISOString().slice(0,10),time:'',competitionType:'',competition:'',encounter:'',facility:'',venue:'',delegate:'',ref1:'',ref2:''};state.opponent={name:'Avversaria',logo:''};state.home=true;state.selected=state.athletes.filter(a=>!a.archived).slice(0,15).map(a=>a.id);state.events=[];state.timeouts=[null,null];save();renderAll();toast('Nuova partita')}};$('backupExport').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`referto-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('backupImportBtn').onclick=()=>$('backupImport').click();$('backupImport').onchange=()=>{const f=$('backupImport').files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!x.settings||!Array.isArray(x.athletes))throw 0;state={...empty(),...x};if(!Array.isArray(state.seasons)||!state.seasons.length)state.seasons=[{id:'season-default',name:'2026/2027'}];state.currentSeasonId=state.currentSeasonId&&state.seasons.some(q=>q.id===state.currentSeasonId)?state.currentSeasonId:state.seasons[0].id;state.match=state.match||{};state.match.seasonId=state.match.seasonId&&state.seasons.some(q=>q.id===state.match.seasonId)?state.match.seasonId:state.currentSeasonId;(state.saved||[]).forEach(q=>{if(!q.seasonId)q.seasonId=state.currentSeasonId;if(q.snapshot&&!q.snapshot.seasonId)q.snapshot.seasonId=q.seasonId});save();renderAll();toast('Backup importato')}catch{toast('Backup non valido')}};r.readAsText(f)};
$('seasonSelect').onchange=()=>{state.currentSeasonId=$('seasonSelect').value;state.match.seasonId=state.currentSeasonId;saveSeasonChange();renderHeader();renderArchive();renderSavedStats();toast('Stagione selezionata')};$('addSeasonBtn').onclick=addSeason;$('renameSeasonBtn').onclick=renameSeason;$('deleteSeasonBtn').onclick=deleteSeason;
// dialog close buttons
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDialog(b.dataset.close));
$('sTeamLogo').onchange=()=>readImage($('sTeamLogo'),v=>{state.settings.teamLogo=v;$('teamLogoPreview').innerHTML=`<img src="${v}">`;save()});$('sOppLogo').onchange=()=>readImage($('sOppLogo'),v=>{state.opponent.logo=v;$('oppLogoPreview').innerHTML=`<img src="${v}">`;save()});
// period selection
 document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{currentPeriod=Number(b.dataset.period);document.querySelectorAll('.period').forEach(x=>x.classList.toggle('active',x===b));renderScore()});
bindTimeInput($('eventTime'));
ensureRoster();renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
